name: filc_stat_graph
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.36.0
  http: ^0.13.1
  intl: ^0.17.0

flutter:
  uses-material-design: true
